name: espresso_challange
description: "A new Flutter project."

publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: '>=3.3.4 <4.0.0'

dependencies:
  flutter:
    sdk: flutter
  cached_network_image: ^3.3.1
  equatable: ^2.0.5
  fl_chart: ^0.68.0
  flutter_bloc: ^8.1.5
  flutter_widget_from_html: ^0.15.0
  intl: ^0.19.0
  provider: ^6.1.2
  share_plus: ^9.0.0
  shared_preferences: ^2.2.3
  sqlite3_flutter_libs: ^0.5.21
  api:
    path: ../api
    # git:
    #   url: https://github.com/Jaxiii/espresso-challenge-api.git
    #   ref: main

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_native_splash: ^2.4.0
  flutter_launcher_icons: ^0.13.1
  flutter_lints: ^3.0.0

flutter_native_splash:
  color: "#B4A270"
  image: assets/images/logo.png
  web: false

  flutter_launcher_icons: "^0.13.1"

flutter_launcher_icons:
  android: "launcher_icon"
  ios: true
  image_path: "assets/icon/icon.png"
  min_sdk_android: 21 

flutter:

  uses-material-design: true

  assets:
    - assets/images/logo.png

